02/23/2023 07:03:52 PM : logging_confiq.logger : 
Traceback (most recent call last):
  File "C:\Users\RJ EMPIRE\Desktop\Django\FundooNotes\Notes\views.py", line 64, in put
    r = RedisCrud().update_note_in_redis(note_id, request.data, request.user.id)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RJ EMPIRE\Desktop\Django\FundooNotes\Notes\redis_utils.py", line 61, in update_note_in_redis
    self.redis.set(user_id, json.dumps(notes_dict.values))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type builtin_function_or_method is not JSON serializable
02/23/2023 07:03:52 PM : logging_confiq.logger : 
Traceback (most recent call last):
  File "C:\Users\RJ EMPIRE\Desktop\Django\FundooNotes\Notes\views.py", line 64, in put
    r = RedisCrud().update_note_in_redis(note_id, request.data, request.user.id)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RJ EMPIRE\Desktop\Django\FundooNotes\Notes\redis_utils.py", line 61, in update_note_in_redis
    self.redis.set(user_id, json.dumps(notes_dict.values))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type builtin_function_or_method is not JSON serializable
02/23/2023 07:14:36 PM : logging_confiq.logger : 
Traceback (most recent call last):
  File "C:\Users\RJ EMPIRE\Desktop\Django\FundooNotes\Notes\views.py", line 64, in put
    r = RedisCrud().update_note_in_redis(note_id, request.data, request.user.id)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RJ EMPIRE\Desktop\Django\FundooNotes\Notes\redis_utils.py", line 61, in update_note_in_redis
    self.redis.set(user_id, json.dumps(notes_dict.values()))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type dict_values is not JSON serializable
02/23/2023 07:14:36 PM : logging_confiq.logger : 
Traceback (most recent call last):
  File "C:\Users\RJ EMPIRE\Desktop\Django\FundooNotes\Notes\views.py", line 64, in put
    r = RedisCrud().update_note_in_redis(note_id, request.data, request.user.id)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RJ EMPIRE\Desktop\Django\FundooNotes\Notes\redis_utils.py", line 61, in update_note_in_redis
    self.redis.set(user_id, json.dumps(notes_dict.values()))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type dict_values is not JSON serializable
